# @package _global_
data:
  train_data_path: data/policy_data.json
  val_data_dir: data/val
  test_data_dir: data/test
  train_dataloader_conf:
    batch_size: 512
    num_workers: 0
#  val_dataloader_conf:
#    batch_size: 512
#    num_workers: 4
#  test_dataloader_conf:
#    batch_size: 512
#    num_workers: 4

network_conf:
  board_size: 10
  in_channels: 2
  residual_channels: 32
  residual_layers: 8

train:
  learning_rate: 0.05
  run_test: false

pl_trainer: 
  weights_summary: top
  max_epochs: 5
  #progress_bar_refresh_rate: 25
  gpus: 1
  auto_lr_find: false

mcts_bot:
  _target_: PVbot.MCTSPolicyValueBot
  model_path: "../../2021-12-13/22-35-50/models/latest.ckpt"
  numIterations: 2
  c_puct: 2

bot_test:
  num_games: 2
  break_on_loose: False
  store_games: True
  store_path: "../../../data/mcts_data.json"
