data:
  train_data_path: data/policy_data.json
  val_data_dir: data/val
  test_data_dir: data/test
  train_dataloader_conf:
    batch_size: 512
    num_workers: 0
#  val_dataloader_conf:
#    batch_size: 512
#    num_workers: 4
#  test_dataloader_conf:
#    batch_size: 512
#    num_workers: 4

network_conf:
  board_size: 10
  in_channels: 2
  residual_channels: 32
  residual_layers: 8

train:
  learning_rate: 0.05
  run_test: false

pl_trainer: 
  weights_summary: top
  max_epochs: 50
  #progress_bar_refresh_rate: 25
  gpus: 1
  auto_lr_find: false
