# Note: if paths start with '/', they are taken relative to the directory of main.py, otherwise it is relative to the hydra working directory

defaults:
  - _self_
  # - player1: mcts_nn2
  # - player1: mcts_nn2
  # - player1: random_search_winning
  # - player2: random_search_winning
  - player1: random_nolook
  - player2: random_nolook
  - network_conf: small
  #- network_conf: huge

general:
  board_size: 10
  mode: "play"
  # mode: "train"
  #mode: "iterate"

#### PLAY ####
play:
  workers: 1
  num_games: 10
  #store_path: "/data/small-100.json"
  #store_path: "/data/slow-games-1.json"
  store_path: null
  game_viewer: false
  random_color: False
  #store_path: "/data/games_gen2.1.json"
  log_pv: True

#### TRAINING ####
general_train:
  #input_model_path: "/models/small_test4.ckpt"
  input_model_path: null
  output_model_path: "/models/latest.ckpt"

data:
  train_data_path:
    [
      "/data/slow-games-1.json",
      "/data/slow-iteration-games-0.json",
      "/data/slow-iteration-games-1.json",
      "/data/slow-iteration-games-2.json",
      "/data/slow-iteration-games-3.json",
      "/data/slow-iteration-games-4.json",
      "/data/slow-iteration-games-5.json",
    ]
  train_val_split: 0.9
  train_dataloader_conf:
    batch_size: 512
    num_workers: 5

train:
  run_test: false
  optimizer:
    lr: 0.001
    momentum: 0.9
    nesterov: True
    weight_decay: 0.003

pl_trainer:
  max_epochs: 10
  #progress_bar_refresh_rate: 25
  accelerator: "auto"
  auto_lr_find: True

#### ITERATION ####
iterate:
  model_start_path: "/models/slow-iteration-model-6.ckpt"
  #model_start_path: "/models/large_test1.ckpt"
  num_iterations: 100
  # number of games to play against last model with each color (total number is twice that)
  num_evaluation_games: 20
  # percentage that has to be won at least to continue with model
  winning_threshold: 0.6
  # list of previously generated data that can be used for training
  game_data_files:
    [
      "/data/slow-games-1.json",
      "/data/slow-iteration-games-0.json",
      "/data/slow-iteration-games-1.json",
      "/data/slow-iteration-games-2.json",
      "/data/slow-iteration-games-3.json",
      "/data/slow-iteration-games-4.json",
      "/data/slow-iteration-games-5.json",
    ]
  # number of positions that are at least used for training (if available)
  # We only use whole files and take the smallest number of past files such
  # we have at least this number of positions to train on
  num_past_train_positions: 50000
