# Note: if paths start with '/', they are taken relative to the directory of main.py, otherwise it is relative to the hydra working directory

defaults:
  - _self_
  - player@player1: mcts_nn2
  - player@player2: human
  # - player@player2: random_search_winning
  # - player@player2: random_search_losing
  # - player@player2: random_nolook
  - network_conf@network_conf.small: small
  - network_conf@network_conf.small_legacy: small_legacy
  - network_conf@network_conf.mid: mid
  - network_conf@network_conf.mid2: mid2

general:
  board_size: 10
  # mode: "play"
  # mode: "train"
  # mode: "iterate"
  mode: "eval"

#### PLAY ####
play:
  workers: 4
  num_games: 1
  store_path: null
  game_viewer: false
  random_color: false
  log_pv: false

#### TRAINING ####
general_train:
  network_conf: ${network_conf.mid}
  input_model_path: null
  output_model_path: "/models/latest.ckpt"

data:
  train_data_path:
    [
      "/data/iteration_games/games_200-1.json",
      "/data/iteration_games/games_200-1.json",
      "/data/iteration_games/games-0.json",
      "/data/iteration_games/games-1.json",
      "/data/iteration_games/games-2.json",
      "/data/iteration_games/games-3.json",
      "/data/iteration_games/games-4.json",
      "/data/iteration_games/games-5.json",
      "/data/iteration_games/games-6.json",
      "/data/iteration_games/games-7.json",
      "/data/iteration_games/games-8.json",
      "/data/iteration_games/games-9.json",

      "/data/iteration_games_cont/games-0.json",
      "/data/iteration_games_cont/games-1.json",
      "/data/iteration_games_cont/games-2.json",
      "/data/iteration_games_cont/games-3.json",
      "/data/iteration_games_cont/games-4.json",
      "/data/iteration_games_cont/games-5.json",
      "/data/iteration_games_cont/games-6.json",
      "/data/iteration_games_cont/games-7.json",
      "/data/iteration_games_cont/games-8.json",
      "/data/iteration_games_cont/games-9.json",
      "/data/iteration_games_cont/games-10.json",
      "/data/iteration_games_cont/games-11.json",
      "/data/iteration_games_cont/games-12.json",
      "/data/iteration_games_cont/games-13.json",
      "/data/iteration_games_cont/games-14.json",
      "/data/iteration_games_cont/games-15.json",
      "/data/iteration_games_cont/games-16.json",
      "/data/iteration_games_cont/games-17.json",
      "/data/iteration_games_cont/games-18.json",
      "/data/iteration_games_cont/games-19.json",
    ]
  train_val_split: 0.9
  train_dataloader_conf:
    batch_size: 128
    num_workers: 0

train:
  run_test: false
  optimizer:
    lr: 0.0001
    momentum: 0.9
    nesterov: True
    weight_decay: 0.000001

pl_trainer:
  max_epochs: 1

#### ITERATION ####
iterate:
  model_start_path: /models/iteration_models_cont2-mid/model-10.ckpt
  num_iterations: 1000
  # number of games to play against last model with each color (total number is twice that)
  num_evaluation_games: 20
  # percentage that has to be won at least to continue with model
  winning_threshold: 0.6
  # list of previously generated data that can be used for training
  game_data_files:
    [
      "/data/iteration_games/games_200-1.json",
      "/data/iteration_games/games_200-1.json",
      "/data/iteration_games/games-0.json",
      "/data/iteration_games/games-1.json",
      "/data/iteration_games/games-2.json",
      "/data/iteration_games/games-3.json",
      "/data/iteration_games/games-4.json",
      "/data/iteration_games/games-5.json",
      "/data/iteration_games/games-6.json",
      "/data/iteration_games/games-7.json",
      "/data/iteration_games/games-8.json",
      "/data/iteration_games/games-9.json",
      "/data/iteration_games_cont/games-0.json",
      "/data/iteration_games_cont/games-1.json",
      "/data/iteration_games_cont/games-2.json",
      "/data/iteration_games_cont/games-3.json",
      "/data/iteration_games_cont/games-4.json",
      "/data/iteration_games_cont/games-5.json",
      "/data/iteration_games_cont/games-6.json",
      "/data/iteration_games_cont/games-7.json",
      "/data/iteration_games_cont/games-8.json",
      "/data/iteration_games_cont/games-9.json",
      "/data/iteration_games_cont/games-10.json",
      "/data/iteration_games_cont/games-11.json",
      "/data/iteration_games_cont/games-12.json",
      "/data/iteration_games_cont/games-13.json",
      "/data/iteration_games_cont/games-14.json",
      "/data/iteration_games_cont/games-15.json",
      "/data/iteration_games_cont/games-16.json",
      "/data/iteration_games_cont/games-17.json",
      "/data/iteration_games_cont/games-18.json",
      "/data/iteration_games_cont/games-19.json",
      "/data/iteration_games_cont2-mid/games-0.json",
      "/data/iteration_games_cont2-mid/games-1.json",
      "/data/iteration_games_cont2-mid/games-2.json",
      "/data/iteration_games_cont2-mid/games-3.json",
      "/data/iteration_games_cont2-mid/games-4.json",
      "/data/iteration_games_cont2-mid/games-5.json",
      "/data/iteration_games_cont2-mid/games-6.json",
      "/data/iteration_games_cont2-mid/games-7.json",
      "/data/iteration_games_cont2-mid/games-8.json",
      "/data/iteration_games_cont2-mid/games-9.json",
      "/data/iteration_games_cont2-mid/games-10.json",
      "/data/iteration_games_cont2-mid/games-11.json",
      "/data/iteration_games_cont2-mid/games-12.json",
    ]
  # number of positions that are at least used for training (if available)
  # We only use whole files and take the smallest number of past files such
  # we have at least this number of positions to train on
  num_past_train_positions: 200000

eval:
  num_evaluation_games: 50
  results_path: /data/eval_results.json
  models:
    - player: /conf/player/random_nolook.yaml
    - player: /conf/player/random_search_winning.yaml
    - player: /conf/player/random_search_losing.yaml
    - player: /conf/player/mcts_nn.yaml
      path: null
    - player: /conf/player/mcts_nn.yaml
      path: /models/iteration_models/model-1.ckpt
    - player: /conf/player/mcts_nn.yaml
      path: /models/iteration_models/model-5.ckpt
    - player: /conf/player/mcts_nn.yaml
      path: /models/iteration_models/model-10.ckpt
    - player: /conf/player/mcts_nn.yaml
      path: /models/iteration_models_cont/model-9.ckpt
    - player: /conf/player/mcts_nn.yaml
      path: /models/iteration_models_cont/model-19.ckpt
    - player: /conf/player/mcts_nn2_eval.yaml
      path: /models/iteration_models_cont/mid-trained_all_data.ckpt
    - player: /conf/player/mcts_nn2_eval.yaml
      path: /models/iteration_models_cont2-mid/model-1.ckpt
    - player: /conf/player/mcts_nn2_eval.yaml
      path: /models/iteration_models_cont2-mid/model-5.ckpt
    - player: /conf/player/mcts_nn2_eval.yaml
      path: /models/iteration_models_cont2-mid/model-10.ckpt
    - player: /conf/player/mcts_nn2_eval.yaml
      path: /models/iteration_models_cont3-mid/model-1.ckpt
    - player: /conf/player/mcts_nn2_eval.yaml
      path: /models/iteration_models_cont3-mid/model-3.ckpt
    - player: /conf/player/mcts_nn2_eval.yaml
      path: /models/iteration_models_cont3-mid/model-4.ckpt
    - player: /conf/player/mcts_nn2_eval.yaml
      path: /models/iteration_models_cont3-mid/model-5.ckpt
